/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rp_jni_test_JniClass */

#ifndef _Included_com_rp_jni_test_JniClass
#define _Included_com_rp_jni_test_JniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rp_jni_test_JniClass
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_rp_jni_1test_JniClass_getString
  (JNIEnv *, jobject , jstring , jint ,jboolean);

#ifdef __cplusplus
}
#endif
#endif
